version: '3.5'

services: 
  angular-service:
    container_name: med-mais-container-1
    build: ./
    volumes:
    - './:/usr/src/app'
    ports:
    - "4201:4200"
    command: /bin/sh -c "npm start"